version: 2.1

jobs:
  lint:  
    docker:
      - image: cimg/node:16.8
    steps:
      # Checkout the code as the first step.
      - checkout
      # Create a folder for results to live in
      - run: "[ -d lint-results ] || mkdir lint-results"
      - run:
          name: Run Spectral Lint
          command: 
            npx @stoplight/spectral-cli lint openapi.yaml
              -o lint-results/junit.xml
              -f junit 
      - store_test_results:
          path: lint-results
          
workflows:
  sample: 
    jobs:
      - lint
